import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  researchSidebar: [
    {
      type: 'category',
      label: 'Context & Landscape',
      link: {type: 'generated-index', description: 'What is LongMemEval-S, who are the competitors, and what does the landscape look like.'},
      items: [{type: 'autogenerated', dirName: '01-context'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'generated-index', description: "Engram's pipeline design: ingestion, storage, retrieval, and answering."},
      items: [{type: 'autogenerated', dirName: '02-architecture'}],
    },
    {
      type: 'category',
      label: 'The Journey',
      link: {type: 'generated-index', description: 'From 0% to 95.8% — eleven phases of iterative engineering'},
      items: [{type: 'autogenerated', dirName: '03-journey'}],
    },
    {
      type: 'category',
      label: 'Forensics',
      link: {type: 'generated-index', description: 'Deep analysis of failures — from 58 at 88.4% to 21 at 95.8%.'},
      items: [{type: 'autogenerated', dirName: '04-forensics'}],
    },
    {
      type: 'category',
      label: 'Dead Ends & Failed Experiments',
      link: {type: 'generated-index', description: 'Everything we tried that didn\'t work, and the engineering discipline rules extracted from $2,500+ of experiments.'},
      items: [{type: 'autogenerated', dirName: '05-dead-ends'}],
    },
    {
      type: 'category',
      label: 'Lessons & Future',
      link: {type: 'generated-index', description: 'Key insights and the path forward to 95%+.'},
      items: [{type: 'autogenerated', dirName: '06-lessons'}],
    },
    {
      type: 'category',
      label: 'Appendices',
      link: {type: 'generated-index', description: 'Full benchmark run history, academic references, execution logs, and archived prompts.'},
      items: [
        'glossary',
        {type: 'autogenerated', dirName: 'appendices'},
      ],
    },
  ],
};

export default sidebars;
